services:
  qr-generator:
    image: saladtechnologies/stable-fast-qr-code
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      - HOST=*
      - PORT=1234
      - CIVITAI_CONTROLNET_MODEL=122143
      - CIVITAI_CHECKPOINT_MODEL=128713
      - MODEL_DIR=/models
    volumes:
      # Mount a local directory to cache model files after they load
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
